project_name: mlflow-test
team: ml

experiment:
  name: Regressor Random Forest
  description: change description

run:
  description: Some description.
  random_state: 0
  model:
    params:
      n_estimators: 2
      max_depth: 70
      max_features: 15
